from enum import Enum
from typing import Any, Protocol, runtime_checkable


class IntegrationType(str, Enum):
    LMS = "lms"
    CALENDAR = "calendar"
    CLOUD_STORAGE = "cloud_storage"
    NOTIFICATION = "notification"
    IDENTITY_PROVIDER = "identity_provider"
    VIDEO_CONFERENCING = "video_conferencing"
    INSTITUTION_PORTAL = "institution_portal"


@runtime_checkable
class LMSIntegration(Protocol):
    async def sync_courses(self) -> list[dict[str, Any]]: ...
    async def sync_enrollments(self) -> list[dict[str, Any]]: ...
    async def sync_grades(self) -> list[dict[str, Any]]: ...
    async def push_content(self, content: dict[str, Any]) -> dict[str, Any]: ...


@runtime_checkable
class CalendarIntegration(Protocol):
    async def list_events(self, start: str, end: str) -> list[dict[str, Any]]: ...
    async def create_event(self, event: dict[str, Any]) -> dict[str, Any]: ...
    async def update_event(self, event_id: str, event: dict[str, Any]) -> dict[str, Any]: ...
    async def delete_event(self, event_id: str) -> None: ...


@runtime_checkable
class CloudStorageIntegration(Protocol):
    async def upload_file(self, path: str, data: bytes, content_type: str) -> dict[str, Any]: ...
    async def download_file(self, path: str) -> bytes: ...
    async def list_files(self, prefix: str = "") -> list[dict[str, Any]]: ...
    async def delete_file(self, path: str) -> None: ...


@runtime_checkable
class IdentityProviderIntegration(Protocol):
    async def authenticate(self, token: str) -> dict[str, Any] | None: ...
    async def sync_users(self) -> list[dict[str, Any]]: ...
    async def validate_token(self, token: str) -> bool: ...


@runtime_checkable
class NotificationProviderIntegration(Protocol):
    async def send_notification(self, recipient: str, message: dict[str, Any]) -> dict[str, Any]: ...
    async def send_bulk(self, recipients: list[str], message: dict[str, Any]) -> list[dict[str, Any]]: ...
